global:
  work_dir: /home/deploy_trunk/
  dest_dir: /home/deploy/

tasks:
  init:
    - module: Confirm
      name: confirm
      config:
        msg: "really deploy app? [y/n]"

  process:
    - module: Rsync
      name: deploy_plack
      config:
        user: app
        source: "[% work_dir %][% project %]"
        dest: "[% server %]:[% dest_dir %]"
        dry_run: 1
        archive:  1
        compress: 1
        rsh:      ssh
        update:   1
        verbose:  1
        delete:   0
        progress: 1
        include: ['*.pl','*.cgi']
        exclude: ['*']
        filter: ['+ lib', '- .svn']

projects:
  example.com:
    servers:
      - app001
      - app002
      - app003
      - app004
      - worker001
      - worker002
  xyz.localhost:
    servers:
      - db001
      - db002

